import { readdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { imageSize } from 'image-size'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(__dirname, '..')
const portfolioDir = path.join(root, 'public', 'portfolio')
const galleryTsPath = path.join(root, 'src', 'data', 'gallery.ts')
const enLocalePath = path.join(root, 'src', 'locales', 'en.json')
const heLocalePath = path.join(root, 'src', 'locales', 'he.json')

const CATEGORIES = ['selected-work', 'full-book-spread']
const IMAGE_EXTENSIONS = new Set(['.jpg', '.jpeg', '.png', '.webp', '.gif', '.avif'])

/** Pinned first/last for selected-work; everything between sorts by spread proportion. */
const SELECTED_WORK_ORDER = {
  first: ['2.jpg', '3 3.jpg', '3.jpg'],
  last: ['10 2.jpg', '9 2.jpg', '11.jpg'],
}

/** Typical double-page book spread (width / height). */
const IDEAL_SPREAD_RATIO = 5787 / 2717

function naturalCompare(a, b) {
  return a.localeCompare(b, undefined, { numeric: true, sensitivity: 'base' })
}

/** Lower = closer to a professional spread proportion. */
function proportionDistance(width, height, idealRatio = IDEAL_SPREAD_RATIO) {
  const ratio = width / height
  return Math.abs(Math.log(ratio / idealRatio))
}

function compareByProportion(a, b) {
  const byProportion =
    proportionDistance(a.width, a.height) - proportionDistance(b.width, b.height)
  if (byProportion !== 0) return byProportion
  return naturalCompare(a.filename, b.filename)
}

function sortGalleryEntries(category, entries) {
  if (category === 'selected-work') {
    const firstSet = new Set(SELECTED_WORK_ORDER.first)
    const lastSet = new Set(SELECTED_WORK_ORDER.last)
    const byName = new Map(entries.map((entry) => [entry.filename, entry]))

    const leading = SELECTED_WORK_ORDER.first
      .map((name) => byName.get(name))
      .filter(Boolean)
    const trailing = SELECTED_WORK_ORDER.last
      .map((name) => byName.get(name))
      .filter(Boolean)
    const middle = entries
      .filter((entry) => !firstSet.has(entry.filename) && !lastSet.has(entry.filename))
      .sort(compareByProportion)

    return [...leading, ...middle, ...trailing]
  }

  return [...entries].sort(compareByProportion)
}

function isImageFile(name) {
  if (name.startsWith('.')) return false
  return IMAGE_EXTENSIONS.has(path.extname(name).toLowerCase())
}

function portfolioImage(category, filename) {
  return `/portfolio/${category}/${encodeURIComponent(filename)}`
}

function escapeString(value) {
  return value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")
}

async function scanCategory(category) {
  const dir = path.join(portfolioDir, category)
  let names = []

  try {
    names = await readdir(dir)
  } catch (error) {
    if (error && typeof error === 'object' && 'code' in error && error.code === 'ENOENT') {
      return []
    }
    throw error
  }

  const filenames = names.filter(isImageFile)
  const entries = []

  for (const filename of filenames) {
    const filePath = path.join(dir, filename)
    const buffer = await readFile(filePath)
    const dimensions = imageSize(buffer)

    if (!dimensions.width || !dimensions.height) {
      throw new Error(`Could not read dimensions for ${filePath}`)
    }

    entries.push({
      filename,
      width: dimensions.width,
      height: dimensions.height,
    })
  }

  const sorted = sortGalleryEntries(category, entries)
  const usedIds = new Set()

  return sorted.map((entry, index) => {
    const slug = entry.filename
      .replace(/\.[^.]+$/, '')
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '')
      .slice(0, 48)

    const base = `${category}-${slug || String(index + 1).padStart(2, '0')}`
    let id = base
    let suffix = 2
    while (usedIds.has(id)) {
      id = `${base}-${suffix}`
      suffix += 1
    }
    usedIds.add(id)

    return {
      id,
      category,
      image: portfolioImage(category, entry.filename),
      width: entry.width,
      height: entry.height,
      filename: entry.filename,
    }
  })
}

function renderGalleryTs(items) {
  const lines = items.map((item) => {
    const parts = [
      `    id: '${escapeString(item.id)}'`,
      `    category: '${item.category}'`,
      `    image: '${escapeString(item.image)}'`,
      `    width: ${item.width}`,
      `    height: ${item.height}`,
    ]
    return `  {\n${parts.join(',\n')},\n  }`
  })

  return `import type { GalleryCategory, GalleryItem } from '@/models/types'

/** Auto-generated by \`npm run gallery:sync\` — do not edit by hand. */
export const GALLERY_CATEGORIES: GalleryCategory[] = ['selected-work', 'full-book-spread']

export const galleryItems: GalleryItem[] = [
${lines.join(',\n')}
]
`
}

async function updateLocale(localePath, items) {
  const raw = await readFile(localePath, 'utf8')
  const locale = JSON.parse(raw)

  if (!locale.gallery) {
    throw new Error(`Missing gallery section in ${localePath}`)
  }

  delete locale.gallery.untitled
  delete locale.gallery.viewWork
  delete locale.gallery.items

  await writeFile(localePath, `${JSON.stringify(locale, null, 2)}\n`, 'utf8')
}

async function main() {
  const allItems = []

  for (const category of CATEGORIES) {
    const items = await scanCategory(category)
    allItems.push(...items)
    console.log(`  ${category}: ${items.length} image(s)`)
  }

  await writeFile(galleryTsPath, renderGalleryTs(allItems), 'utf8')
  await updateLocale(enLocalePath, allItems)
  await updateLocale(heLocalePath, allItems)

  console.log(`\nSynced ${allItems.length} gallery image(s) → src/data/gallery.ts`)
}

main().catch((error) => {
  console.error('gallery:sync failed:', error)
  process.exit(1)
})
